### ISSUE TITLE
mute等指令中的mirv_snd_filter参数问题

### ISSUE THREAD

**Issue by Fachep** [Purple-CSGO/CSGO-Config-Presets#11]

**Comment by Fachep** [comment]
hlae.cfg中
```
alias mute      "snd_roundstart_volume 0;snd_roundend_volume 0;snd_mapobjective_volume 0;snd_tensecondwarning_volume 0;snd_deathcamera_volume 0;snd_mvp_volume 0;mirv_snd_filter block +player\\vo\\\*;mirv_snd_filter block +radio\\\*"
```
其中mirv_snd_filter的参数的反斜线似乎被转义后没有发挥作用：
![image](https://user-images.githubusercontent.com/31302548/146687998-fb85eb42-935d-457b-bcc2-9d9e5c524483.png)
如图，0和1是mute命令添加的mask，2是手动添加的，0并没有发挥作用

**Comment by Purple-CSGO** [comment]
这个后来在主分支修复过了，就是没发布更新，有空我再小改一下发个1.6a吧
