### ISSUE TITLE
刚才打官匹因为那个练习脚本被服务器T出去了

### ISSUE THREAD

**Issue by mrdobejelly** [Purple-CSGO/CSGO-Config-Presets#2]
我并没有加载practice.cfg，但是服务器还是提示practiceExt.nut和服务器不匹配。不是偶发性的。

**Comment by Purple-CSGO** [comment]
我是之前出现过一次，后面就好了。
不过讲道理这是v社自己的vscript，用于地图指令和本地的，在线游戏本来也用不了，这也踢出有点离谱。
下个版本默认用cfg的方法吧，vscript放到可选里面，不过效果不完美

**Comment by zxbforever** [comment]
+1 我也遇到过 蚌埠住了
