### ISSUE TITLE
陆续的一些小问题

### ISSUE THREAD

**Issue by asayake777** [Purple-CSGO/CSGO-Config-Presets#5]
1.practise中控制台输出的杀死和消灭字样被和谐了
2.practise中已经绑定了k为kill，没必要再输出中再显示；删除添加放置也是
3.建议practise中增加一键换图功能
4.开局按到o / ]人物会传到地图外，希望在未保存ab点的情况下按到这两个键能保持原地不动并提示先保存位置

**Comment by asayake777** [comment]
1.practise中已经绑定了k为kill，没必要再输出中再显示
2.建议practise中增加一键换图功能

**Comment by asayake777** [comment]
请问控制台输出内容那么整齐是怎么做到的🤐

**Comment by Purple-CSGO** [comment]
> 
> 
> 请问控制台输出内容那么整齐是怎么做到的🤐

`\t` 和 空格 游戏里反复测试微调

**Comment by Purple-CSGO** [comment]
> 
> 
> 1.practise中控制台输出的杀死和消灭字样被和谐了
> 2.practise中已经绑定了k为kill，没必要再输出中再显示；删除添加放置也是
> 3.建议practise中增加一键换图功能
> 4.开局按到o / ]人物会传到地图外，希望在未保存ab点的情况下按到这两个键能保持原地不动并提示先保存位置

k是杀死bot，kill是自杀，两个含义不一样

**Comment by asayake777** [comment]
哦哦，抱歉我说错了，我的意思就是已经绑定按键的功能就没必要再在常用指令中出现了
