### ISSUE TITLE
v1.5 待办

### ISSUE THREAD

**Issue by Purple-CSGO** [Purple-CSGO/CSGO-Config-Presets#7]
- [x] 改进过的tab显示net_graph
- [x] 不同cfg之间exec xxx的F11~F12相匹配
- [x] 子弹数和无限弹夹也添加到控制台提示
- [x] r_dynamic
- [x] 改进128tick说明
- [x] 大跳推荐space
- [x] 鼠标中键预设双键
- [x] 增加一组dq推荐的小地图参数
- [x] 语音轮盘相关键位和设置
- [x] 单独出一个`chatwheel.cfg`设置聊天轮盘，可选
- [x] m_yaw 拉伸补偿
- [x] 基于apply_crosshair_code 做投掷准星
- [x] 未保存ab点的情况下按到这两个键能保持原地不动并提示先保存位
- [x] demo自带单个玩家语音屏蔽功能说明

**Comment by asayake777** [comment]
🤩
